# Generated by Django 4.2.7 on 2023-12-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='_cart_id',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
