# Generated by Django 4.2.7 on 2023-12-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_cart_id_cart__cart_id_alter_cart_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_cart_id',
            new_name='cart_id',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='Cart_Item',
        ),
    ]
